<?php

    if (!isset($db)) { require_once __DIR__.'/../config.php'; $db = getDbConnection(); }
    $success = $error = null;
    if (isset($_GET['get_budget'])) {
        $id = (int)$_GET['get_budget'];
        if ($id <= 0) { header('Content-Type: application/json'); echo json_encode(['error'=>'Invalid']); exit; }
        $stmt = $db->prepare("SELECT id,fiscal_year,name,start_date,end_date,approved_date,reference_number,status,total_budgeted FROM budgets WHERE id=?");
        $stmt->bind_param('i',$id); $stmt->execute(); $b=$stmt->get_result()->fetch_assoc(); $stmt->close();
        if(!$b){header('Content-Type:application/json');echo json_encode(['error'=>'Not found']);exit;}
        $ls=$db->prepare("SELECT natural_category_id,functional_category_id,account_id,budgeted_amount,notes FROM budget_lines WHERE budget_id=? ORDER BY id");
        $ls->bind_param('i',$id);$ls->execute();$lines=[];$res=$ls->get_result();
        while($l=$res->fetch_assoc()){$lines[]=['natural_category_id'=>$l['natural_category_id']!==null?(int)$l['natural_category_id']:'','functional_category_id'=>$l['functional_category_id']!==null?(int)$l['functional_category_id']:'','account_id'=>$l['account_id']!==null?(int)$l['account_id']:'','budgeted_amount'=>$l['budgeted_amount'],'notes'=>$l['notes']??''];}
        $ls->close();$b['lines']=$lines;header('Content-Type:application/json');echo json_encode($b);exit;
    }

    if ($_SERVER['REQUEST_METHOD']==='POST') {
        $bid=(int)($_POST['budget_id']??0); $fy=(int)($_POST['fiscal_year']??0); $nm=trim($_POST['name']??''); $sd=$_POST['start_date']??''; $ed=$_POST['end_date']??'';
        if($fy<2000||!$nm||!$sd||!$ed){$error='Fiscal year (2000+), name, start and end date required.';}else{
            $ad=!empty($_POST['approved_date'])?$_POST['approved_date']:null; $rf=trim($_POST['reference_number']??''); $st=$_POST['status']??'draft'; if(!in_array($st,['draft','active','closed']))$st='draft';
            $lns=json_decode($_POST['lines_json']??'[]',true)?:[];
            if($bid>0){$upd=$db->prepare("UPDATE budgets SET fiscal_year=?,name=?,start_date=?,end_date=?,approved_date=?,reference_number=?,status=? WHERE id=?");$upd->bind_param("issssssi",$fy,$nm,$sd,$ed,$ad,$rf,$st,$bid);$upd->execute();$upd->close();}else{$ins=$db->prepare("INSERT INTO budgets (fiscal_year,name,start_date,end_date,approved_date,reference_number,status) VALUES(?,?,?,?,?,?,?)");$ins->bind_param("issssss",$fy,$nm,$sd,$ed,$ad,$rf,$st);if($ins->execute())$bid=$db->insert_id;$ins->close();}
            if($bid>0){
                $del=$db->prepare("DELETE FROM budget_lines WHERE budget_id=?");$del->bind_param('i',$bid);$del->execute();$del->close();
                $insl=$db->prepare("INSERT INTO budget_lines (budget_id,natural_category_id,functional_category_id,account_id,budgeted_amount,notes) VALUES(?,?,?,?,?,?)");$total=0.0;
                foreach($lns as $ln){$na=!empty($ln['natural_category_id'])?(int)$ln['natural_category_id']:null;$fu=!empty($ln['functional_category_id'])?(int)$ln['functional_category_id']:null;$ac=!empty($ln['account_id'])?(int)$ln['account_id']:null;$am=(float)($ln['budgeted_amount']??0);$no=trim($ln['notes']??'');if($am<=0&&$no==='')continue;$total+=$am;$insl->bind_param("iiiids",$bid,$na,$fu,$ac,$am,$no);$insl->execute();}
                $insl->close();$tup=$db->prepare("UPDATE budgets SET total_budgeted=? WHERE id=?");$tup->bind_param("di",$total,$bid);$tup->execute();$tup->close();$success="Budget #{$bid} saved.";
            }else{$error='Save failed: '.$db->error;}
        }
    }

    $budgets_res = $db->query("SELECT id,fiscal_year,name,start_date,end_date,approved_date,reference_number,status,total_budgeted FROM budgets ORDER BY fiscal_year DESC,id DESC");
    $nr=$db->query("SELECT id,name FROM natural_categories WHERE archived=FALSE ORDER BY name"); $nat_opts='<option value="">—</option>'; if($nr){while($n=$nr->fetch_assoc()){$nat_opts.='<option value="'.(int)$n['id'].'">'.htmlspecialchars($n['name']).'</option>';}}
    $fr=$db->query("SELECT id,name FROM functional_categories WHERE archived=FALSE ORDER BY name"); $func_opts='<option value="">—</option>'; if($fr){while($f=$fr->fetch_assoc()){$func_opts.='<option value="'.(int)$f['id'].'">'.htmlspecialchars($f['name']).'</option>';}}
    $ar=$db->query("SELECT id,name FROM accounts WHERE archived=FALSE ORDER BY name"); $acct_opts='<option value="">—</option>'; if($ar){while($a=$ar->fetch_assoc()){$acct_opts.='<option value="'.(int)$a['id'].'">'.htmlspecialchars($a['name']).'</option>';}}
?>

<div class="container-fluid mt-2">
<?php if($success||$error): ?><div class="alert alert-<?= $success?'success':'danger' ?> alert-dismissible py-1 small mb-2"><?= htmlspecialchars($success??$error) ?><button type="button" class="btn-close btn-sm" data-bs-dismiss="alert"></button></div><?php endif; ?>
<div class="d-flex align-items-center mb-2"><h2 class="mb-0 me-3">Budget</h2><button type="button" id="newBudgetBtn" class="btn btn-sm btn-primary">+ New Budget</button></div>
<div class="card mb-3"><div class="card-header py-1"><strong>Existing Budgets</strong> <small class="text-muted">(click to edit)</small></div><div class="table-responsive" style="max-height:160px;overflow:auto"><table class="table table-sm table-hover mb-0"><thead class="table-dark"><tr><th style="width:60px">FY</th><th>Name</th><th>Period</th><th>Status</th><th>Ref#</th><th class="text-end">Total</th></tr></thead><tbody id="budgetTableBody"><?php if($budgets_res&&$budgets_res->num_rows>0){while($b=$budgets_res->fetch_assoc()){$sb=$b['status'];$badge=$sb==='active'?'bg-success':($sb==='closed'?'bg-secondary':'bg-warning text-dark');?><tr data-id="<?= (int)$b['id'] ?>"><td><?= (int)$b['fiscal_year'] ?></td><td><?= htmlspecialchars($b['name']) ?></td><td class="small"><?= htmlspecialchars($b['start_date']) ?>—<?= htmlspecialchars($b['end_date']) ?></td><td><span class="badge <?= $badge ?>"><?= htmlspecialchars($sb) ?></span></td><td class="small"><?= htmlspecialchars($b['reference_number']??'') ?></td><td class="text-end fw-semibold">$<?= number_format($b['total_budgeted'],2) ?></td></tr><?php }}else{?><tr><td colspan="6" class="text-center text-muted py-2">No budgets. Use + New.</td></tr><?php } ?></tbody></table></div></div>
<div class="card"><div class="card-header py-1"><strong id="formTitle">Budget Details</strong></div><div class="card-body py-2"><form id="budgetForm" method="post"><input type="hidden" name="budget_id" id="budget_id"><input type="hidden" name="lines_json" id="lines_json">
<div class="row g-2"><div class="col-auto"><label class="form-label small mb-0">FY*</label><input type="number" id="fiscal_year" name="fiscal_year" class="form-control form-control-sm" style="width:82px" min="2000" required></div><div class="col-md-3"><label class="form-label small mb-0">Name*</label><input type="text" id="name" name="name" class="form-control form-control-sm" required></div><div class="col-auto"><label class="form-label small mb-0">Start*</label><input type="date" id="start_date" name="start_date" class="form-control form-control-sm" required></div><div class="col-auto"><label class="form-label small mb-0">End*</label><input type="date" id="end_date" name="end_date" class="form-control form-control-sm" required></div><div class="col-auto"><label class="form-label small mb-0">Approved</label><input type="date" id="approved_date" name="approved_date" class="form-control form-control-sm"></div><div class="col-md-2"><label class="form-label small mb-0">Ref#</label><input type="text" id="reference_number" name="reference_number" class="form-control form-control-sm"></div><div class="col-auto"><label class="form-label small mb-0">Status</label><select id="status" name="status" class="form-select form-select-sm"><option value="draft">draft</option><option value="active">active</option><option value="closed">closed</option></select></div></div>
<div class="mt-2"><div class="d-flex justify-content-between mb-1"><strong class="small">Budget Lines</strong> (natural/functional/account) <button type="button" id="addLineBtn" class="btn btn-sm btn-outline-primary py-0 px-2">+ Line</button></div><div class="table-responsive"><table class="table table-sm table-bordered mb-1"><thead class="table-light"><tr><th>Natural</th><th>Functional</th><th>Account</th><th style="width:100px">Amount</th><th>Notes</th><th></th></tr></thead><tbody id="linesBody"></tbody></table></div><div class="small"><strong>Total:</strong> $<span id="linesTotal">0.00</span></div></div>
<div class="mt-1"><button type="submit" class="btn btn-sm btn-primary">Save Budget</button> <button type="button" id="clearBtn" class="btn btn-sm btn-outline-secondary ms-1">Clear</button></div></form></div></div>
</div>

<script type="text/plain" id="init-budget-script">
(function(){const form=document.getElementById('budgetForm'),linesBody=document.getElementById('linesBody'),addLineBtn=document.getElementById('addLineBtn'),clearBtn=document.getElementById('clearBtn'),newBtn=document.getElementById('newBudgetBtn'),linesJson=document.getElementById('lines_json'),budgetId=document.getElementById('budget_id'),formTitle=document.getElementById('formTitle'),tbody=document.getElementById('budgetTableBody');const natOpts=`<?= $nat_opts ?>`,funcOpts=`<?= $func_opts ?>`,acctOpts=`<?= $acct_opts ?>`;
function recalc(){let t=0;linesBody.querySelectorAll('tr').forEach(r=>t+=parseFloat(r.querySelector('.line-amount')?.value||0));const e=document.getElementById('linesTotal');if(e)e.textContent=t.toFixed(2);}
function attach(row){if(row.dataset.attached==='1')return;row.dataset.attached='1';const a=row.querySelector('.line-amount'),r=row.querySelector('.remove-line');if(a)a.addEventListener('input',recalc);if(r)r.addEventListener('click',()=>{row.remove();recalc();});}
function mkRow(p){const r=document.createElement('tr');r.innerHTML=`<td><select class="form-select form-select-sm line-nat">${natOpts}</select></td><td><select class="form-select form-select-sm line-func">${funcOpts}</select></td><td><select class="form-select form-select-sm line-acct">${acctOpts}</select></td><td><input type="number" step="0.01" min="0" class="form-control form-control-sm line-amount text-end"></td><td><input type="text" class="form-control form-control-sm line-notes" placeholder=""></td><td><button type="button" class="btn btn-sm btn-outline-danger py-0 px-1 remove-line">×</button></td>`;if(p){const s=(c,v)=>{const el=r.querySelector(c);if(el&&v!=null&&v!=='')el.value=v;};s('.line-nat',p.natural_category_id);s('.line-func',p.functional_category_id);s('.line-acct',p.account_id);const ai=r.querySelector('.line-amount');if(ai&&p.budgeted_amount!=null)ai.value=p.budgeted_amount;const ni=r.querySelector('.line-notes');if(ni)ni.value=p.notes||'';}return r;}
function addL(p){const row=mkRow(p);linesBody.appendChild(row);attach(row);recalc();}
function clrSel(){tbody.querySelectorAll('tr').forEach(r=>r.classList.remove('table-primary'));}
function resetF(){form.reset();budgetId.value='';linesBody.innerHTML='';formTitle.textContent='New Budget';addL();recalc();clrSel();}
function pop(d){budgetId.value=d.id||'';document.getElementById('fiscal_year').value=d.fiscal_year||'';document.getElementById('name').value=d.name||'';document.getElementById('start_date').value=d.start_date||'';document.getElementById('end_date').value=d.end_date||'';document.getElementById('approved_date').value=d.approved_date||'';document.getElementById('reference_number').value=d.reference_number||'';document.getElementById('status').value=d.status||'draft';linesBody.innerHTML='';(d.lines||[]).forEach(l=>addL(l));formTitle.textContent='Edit #'+(d.id||'');recalc();clrSel();const tr=tbody.querySelector('tr[data-id="'+(d.id||'')+'"]');if(tr)tr.classList.add('table-primary');}
tbody.addEventListener('click',e=>{const tr=e.target.closest('tr');if(!tr||!tr.dataset.id)return;clrSel();tr.classList.add('table-primary');fetch('pages/budget.php?get_budget='+tr.dataset.id).then(r=>r.json()).then(d=>{if(d&&!d.error)pop(d);}).catch(console.error);});
if(newBtn)newBtn.addEventListener('click',resetF);if(clearBtn)clearBtn.addEventListener('click',resetF);if(addLineBtn)addLineBtn.addEventListener('click',()=>addL());
form.addEventListener('submit',()=>{const arr=[];linesBody.querySelectorAll('tr').forEach(tr=>{const g=c=>tr.querySelector(c)?tr.querySelector(c).value:'';const na=g('.line-nat'),fu=g('.line-func'),ac=g('.line-acct'),am=parseFloat(g('.line-amount')||'0'),no=g('.line-notes').trim();if(na||fu||ac||am>0||no)arr.push({natural_category_id:na?parseInt(na):null,functional_category_id:fu?parseInt(fu):null,account_id:ac?parseInt(ac):null,budgeted_amount:am,notes:no});});linesJson.value=JSON.stringify(arr);});
resetF();})();
</script>
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" style="display:none" alt="" onload="var s=document.getElementById('init-budget-script');if(s){(new Function(s.textContent))();}this.remove();">

<?php if (isset($db)) { $db->close(); } ?>
